package org.customer.app;

import java.util.List;
import java.util.Scanner;

import org.customer.app.factory.CustomerFactory;
import org.customer.app.factory.CustomerFactoryImpl;
import org.customer.app.model.Customer;
public class App 
{
    private static Scanner scanner=new Scanner(System.in);
	public static void main( String[] args )
    {
        try {
        	
        	Customer customer=null;
        	System.out.println("enter your choice");
        	System.out.println("1.add the datail");
        	System.out.println("2.display the detail");
        	System.out.println("3.update the details");
        	System.out.println("4.delete the details");
        	System.out.println("5.Search the details");
        	int choice=scanner.nextInt();
        	do
        	{
        		 choice=scanner.nextInt();
        		 switch (choice) {
 				case 1:
 					System.out.print("ID: ");
 					int id = scanner.nextInt();
 					System.out.print("NAME: ");
 					String name = scanner.next();
 					System.out.print("EMAIL: ");
 					String email = scanner.next();

 					CustomerFactory impl = new CustomerFactoryImpl();
 					Customer customer = impl.createCustomer(id, name, email);
 					System.out.println(customer.toString());
 					break;

 				case 2:
 					CustomerFactory imp2 = new CustomerFactoryImpl();
 					List<Customer> list = imp2.getAllCustomer();
 					for (Customer c : list) {
 						System.out.println(c);
 					}

 				}
        	}while(choice!=0);
			
			  /*System.out.print("ID: "); int id=scanner.nextInt();
			  
			 
       */
        	/*List<Customer> list=impl.getAllCustomer();
        	for(Customer c:list)
        	{
        		System.out.println(c);
        	}*/
        	
        
			
		} 
        catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
    }
}
